wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    code_path: code/mydpr/main.py
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      4: 3.8.11
      5: 0.10.15
